### ISSUE TITLE
Vendor Dependencies json not correct

### ISSUE THREAD

**Issue by zbross** [REVrobotics/Color-Sensor-v3-Examples#1]
The REV Robotics Color Sensor V3 vendor dependency json file in the example code is not correct and currently points to an invalid address (http://www.revrobotics.com/content/sw/max/sdk/REVColorSensorV3.json), while it should be pointing to http://revrobotics.com/content/sw/color-sensor-v3/sdk/REVColorSensorV3.json.

**Comment by willtoth** [comment]
Thanks for pointing this out, fixed in df392ccbd584d1de5a8303c963f220c587373304
